### ISSUE TITLE
Item selection backgrounds are too bright compared to text color; most text becomes hard to read

### ISSUE THREAD

**Issue by Dupiter-AU** [skaiTF/skyhud#10]
![Screenshot_20240707_222209](https://github.com/skaiTF/skyhud/assets/82429716/70137019-8025-4511-a780-09a9ad525f46)

HUD is fantastic all around, but I can't change loadouts without getting flashbanged. Text becomes completely unreadable when night color adjustment turns on. Turning off item quality borders did not affect the output

I would like to suggest an option for a darker background on backpack and loadout selection screens.

Arch Linux, 16x9 res

I made sure all folders are lowercase

**Comment by skaiTF** [comment]
Hiya! 
Are you using the release version or one of the latest commits? If you're using the latter, I started changing the item rarity borders in [this](https://github.com/skaiTF/skyhud/commit/1a5e283b34940b2daf75a8893286acee7d230c1e) commit but did't finish it, which would result in those unpleasant looking grey rectangles when the item quality borders are turned off. Turning on the borders _should_ turn the rectangles into their respective colors making the text slightly more readable, but it seems changing that option isn't taking any effect on your end so I will have to look into that. Also, now that you've mentioned it, I can imagine it may still be hard to see with night mode color adjustments even when the borders are working properly, so I'll take that into account whenever I pick this up again.
Finally, you mentioned you're on linux. Last week I launched tf2 with my hud on my linux machine for the first time in a couple of years and realized that the linux support needs some work... mainly with respect to fonts and some borders that are not working as intended, so you can expect some fixes in that regard in the next few days.

**Comment by Dupiter-AU** [comment]
Yea I was using the latest commit, that makes more sense. The borders were not in fact changing the colors of the backgrounds so that's probably a bug lol. I look forward to seeing more fixes, I have noticed a couple of icons are slightly cut off

**Comment by aidan-xy** [comment]
as of the latest commit this problem also occurs on windows 16x9, but the entire item box is the color of the item quality, making unique items especially hard to read

![image](https://github.com/user-attachments/assets/8197661c-b7b7-4541-a7d0-1e9072678db4)

![image](https://github.com/user-attachments/assets/196ba6f4-a540-4e4c-b823-fffa70bc3278)

**Comment by pakahenepy** [comment]
![image](https://github.com/user-attachments/assets/32004914-deb0-4fd0-b512-e5ba47185720)

also happening to me (win 11)

**Comment by skaiTF** [comment]
The item borders have been reverted to an older version to fix the readability issues ab3d7d58bce80baa1377f258d33b9ef8eba8f4d7
I will be closing this for now
