### ISSUE TITLE
scoreboard profile pictures not formatting correctly

### ISSUE THREAD

**Issue by aidan-xy** [skaiTF/skyhud#15]
![image](https://github.com/user-attachments/assets/7c78786e-3016-4cda-9707-6739e392f215)

I am on 16x9 Windows using the latest commit as of now. The profile pictures on the scoreboard aren't indented near the name tag and are also slightly squished/cropped. I believe this issue started happening after the scream fortress 2024 update.

how I thought it was supposed to look:
![image](https://github.com/user-attachments/assets/b07fdb9f-c4e5-46d4-b8ee-683115778921)

edit: i think the profile pictures are on top of where the casual badge should be

**Comment by skaiTF** [comment]
Thank you for the heads-up. 
Fixed in 9b12e0dc24c99daf6fb8d4dc933f04eea85efef8
