### ISSUE TITLE
payload race does not show cart progress

### ISSUE THREAD

**Issue by aidan-xy** [skaiTF/skyhud#16]
![image](https://github.com/user-attachments/assets/08ed54f1-ccf4-47a2-95db-a8f93b461129)
I do not know when this issue began happening. 16x9 windows latest commit.

edit: if the ss is unclear both carts are near the end

**Comment by skaiTF** [comment]
Fixed in 4252ce85a2b2eddb2b82a7e11ad1f023f9121d3f
