### ISSUE TITLE
chat size

### ISSUE THREAD

**Issue by pakahenepy** [skaiTF/skyhud#17]
is there any way to change the font size for chat? it looks a little too small for how id like, thank you :)
![image](https://github.com/user-attachments/assets/02dfcb28-d83c-4440-80f7-ae0bbb03e0ca)

**Comment by skaiTF** [comment]
Hi, you can increase the size of the chat font by increasing the `tall` values of the `"ChatFont"` entries  in skyhud/resource/chatscheme.res (around line 290)

**Comment by pakahenepy** [comment]
thank you!
