### ISSUE TITLE
TF2 store

### ISSUE THREAD

**Issue by ADHDEMO** [skaiTF/skyhud#5]
I enjoy your hud it's very helpful and clean but the store part of it I can't manage to get anywhere else except for three categories can you please fix it

**Comment by skaiTF** [comment]
@ADHDEMO hi, would you mind explaining what the issue is in more detail, possibly with screenshots of what you mean by categories? i am having trouble understanding it. thank you :)

**Comment by ADHDEMO** [comment]
<img width="1920" alt="these" src="https://github.com/skaiTF/skyhud/assets/139581443/31add2e4-034b-457f-9add-fd88f1745170">

**Comment by skaiTF** [comment]
The Mann co store menu does not look like that on my end. Try to reinstall the hud and make sure it is the only hud in your custom folder. If you need additional help with this issue, pls message me on discord @skaideer
That screen is supposed to look like this:
![imagem](https://github.com/skaiTF/skyhud/assets/68827456/cf41596f-a9b2-4ccc-b077-69a696701a6c)
